[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "day-01"
harness = false
path = "benches/benchmark.rs"

[dev-dependencies]
divan = "0.1.4"

[dependencies]
