name: Benchmark Updated Directories in PR

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        shell: bash
        run: |
          cargo build --release

      - name: Benchmark updated
        shell: bash
        run: |
          git diff --name-only HEAD^ HEAD | grep '^day-[0-9]*' | awk -F '/' '{print $1}' | uniq | xargs -r cargo bench -q --all-features -p

